trigger:
  branches:
    include:
    - main
  tags:
    include: ['*']

pool:
  vmImage: 'ubuntu'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration)'
    projects: 'src/GcodeInterpreter/GcodeInterpreter.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)'
    artifactName: Build_Package